ci(default-bare): use var, add default-virtualenv for 24.04 and non-virtualenv as experimental, add verify, clean after script

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -25,15 +25,20 @@ jobs:
           - distribution: ubuntu
             version: '24.04'
             suite: default
-            experimental: false
+            experimental: true
           - distribution: ubuntu
             version: '22.04'
             suite: default
+            experimental: false
+          - distribution: ubuntu
+            version: '24.04'
+            suite: default-virtualenv
             experimental: false
     env:
       ANSIBLE_CALLBACKS_ENABLED: profile_tasks
       ANSIBLE_EXTRA_VARS: ""
       ANSIBLE_ROLE: juju4.floss
+      ANSIBLE_SUITE: ${{ matrix.suite }}
 
     steps:
       - uses: actions/checkout@v4
@@ -57,6 +62,7 @@ jobs:
           ansible --version
           cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
           [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
+          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
           { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
       - name: Environment
         run: |
@@ -65,16 +71,21 @@ jobs:
           find -ls
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/${{ matrix.suite }}/default.yml ${ANSIBLE_EXTRA_VARS}
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/${{ matrix.suite }}/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+      - name: verify
+        run: |
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/verify.yml ${ANSIBLE_EXTRA_VARS}
+        env:
+          PY_COLORS: '1'
+          ANSIBLE_FORCE_COLOR: '1'
       - name: On failure
         run: |
-          ansible -i inventory --connection=local -m setup localhost
           systemctl -l --no-pager status
           systemctl -l --no-pager --failed
           ls -l /usr/bin/ | egrep '(python|pip|ansible)'
@@ -87,34 +98,15 @@ jobs:
           ping -c 1 8.8.8.8 || true
         if: ${{ failure() }}
         continue-on-error: true
-      - name: After script - systemd
+      - name: After script - ansible setup
         run: |
-          systemctl -l --no-pager status iptables || true
-          systemd-analyze --no-pager security || true
-          rsyslogd -v
+          ansible -i inventory --connection=local -m setup localhost
         if: ${{ always() }}
         continue-on-error: true
-      - name: After script - etc
+      - name: After script - python
         run: |
-          ls -la /etc
-          ls -la /etc/ssh/
-        continue-on-error: true
-      - name: After script - apt
-        run: |
-          apt show libtsk-dev -a
-          apt show libtsk13 -a
-          apt show libewf -a
-          apt show libewf2 -a
-          sudo apt-get install -y apt-rdepends
-          apt-rdepends libtsk-dev
-        if: ${{ always() }}
-        continue-on-error: true
-      - name: After script - files
-        run: |
-          sudo ls /home/sansforensics
-          sudo ls /home/sansforensics/Desktop
-          ls -lA /usr/local/bin
-          ls -lA /usr/share/remnux
-          ls -lA /etc/apt/sources.list.d
-        if: ${{ always() }}
+          set -x
+          pip3 freeze
+          echo === virtualenv ===
+          /home/runner/env/bin/pip3 freeze
         continue-on-error: true
